/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo.kotlingradle

class App {
    val greeting: String
        get() {
            return "Hello world. Learning GitHub actions"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
