name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Intall pre-reqs
        run: |
          curl -SL "https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip" --output terraform.zip
          unzip terraform.zip
          mv terraform /usr/local/bin
          terraform --version
          rm terraform.zip

      - name: Install TFLint