name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install pre-reqs
        run: |
          curl -SL "https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip" --output terraform.zip
          unzip terraform.zip
          mv terraform /usr/local/bin
          terraform --version
          rm terraform.zip

      - name: Install TFLint
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.25.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          mv tflint /usr/local/bin

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
